// export { default as angularHtml } from 'shiki/langs/angular-html.mjs'
// export { default as angularTs } from 'shiki/langs/angular-ts.mjs'
// export { default as astro } from 'shiki/langs/astro.mjs'
// export { default as blade } from 'shiki/langs/blade.mjs'
// export { default as c } from 'shiki/langs/c.mjs'
// export { default as coffee } from 'shiki/langs/coffee.mjs'
// export { default as cpp } from 'shiki/langs/cpp.mjs'
export { default as css } from 'shiki/langs/css.mjs'
// export { default as glsl } from 'shiki/langs/glsl.mjs'
// export { default as graphql } from 'shiki/langs/graphql.mjs'
// export { default as haml } from 'shiki/langs/haml.mjs'
// export { default as handlebars } from 'shiki/langs/handlebars.mjs'
export { default as html } from 'shiki/langs/html.mjs'
// export { default as htmlDerivative } from 'shiki/langs/html-derivative.mjs'
// export { default as http } from 'shiki/langs/http.mjs'
// export { default as imba } from 'shiki/langs/imba.mjs'
export { default as java } from 'shiki/langs/java.mjs'
// export { default as javascript } from 'shiki/langs/javascript.mjs'
// export { default as jinja } from 'shiki/langs/jinja.mjs'
// export { default as jison } from 'shiki/langs/jison.mjs'
// export { default as json } from 'shiki/langs/json.mjs'
// export { default as json5 } from 'shiki/langs/json5.mjs'
export { default as jsonc } from 'shiki/langs/jsonc.mjs'
// export { default as jsonl } from 'shiki/langs/jsonl.mjs'
// export { default as jsx } from 'shiki/langs/jsx.mjs'
// export { default as julia } from 'shiki/langs/julia.mjs'
// export { default as less } from 'shiki/langs/less.mjs'
export { default as markdown } from 'shiki/langs/markdown.mjs'
// export { default as marko } from 'shiki/langs/marko.mjs'
// export { default as mdc } from 'shiki/langs/mdc.mjs'
// export { default as mdx } from 'shiki/langs/mdx.mjs'
export { default as php } from 'shiki/langs/php.mjs'
// export { default as postcss } from 'shiki/langs/postcss.mjs'
// export { default as pug } from 'shiki/langs/pug.mjs'
export { default as python } from 'shiki/langs/python.mjs'
// export { default as r } from 'shiki/langs/r.mjs'
// export { default as regexp } from 'shiki/langs/regexp.mjs'
// export { default as sass } from 'shiki/langs/sass.mjs'
// export { default as scss } from 'shiki/langs/scss.mjs'
export { default as shellscript } from 'shiki/langs/shellscript.mjs'
// export { default as sql } from 'shiki/langs/sql.mjs'
// export { default as stylus } from 'shiki/langs/stylus.mjs'
// export { default as svelte } from 'shiki/langs/svelte.mjs'
// export { default as tsTags } from 'shiki/langs/ts-tags.mjs'
export { default as tsx } from 'shiki/langs/tsx.mjs'
export { default as typescript } from 'shiki/langs/typescript.mjs'
export { default as vue } from 'shiki/langs/vue.mjs'
// export { default as vueHtml } from 'shiki/langs/vue-html.mjs'
// export { default as wasm } from 'shiki/langs/wasm.mjs'
// export { default as wgsl } from 'shiki/langs/wgsl.mjs'
export { default as xml } from 'shiki/langs/xml.mjs'
export { default as yaml } from 'shiki/langs/yaml.mjs'

// export { default as bat } from 'shiki/langs/bat.mjs'
// export { default as csharp } from 'shiki/langs/csharp.mjs'
// export { default as dart } from 'shiki/langs/dart.mjs'
// export { default as cmake } from 'shiki/langs/cmake.mjs'
// export { default as csv } from 'shiki/langs/csv.mjs'
export { default as diff } from 'shiki/langs/diff.mjs'
// export { default as docker } from 'shiki/langs/docker.mjs'
// export { default as dotenv } from 'shiki/langs/dotenv.mjs'
export { default as go } from 'shiki/langs/go.mjs'
// export { default as groovy } from 'shiki/langs/groovy.mjs'
export { default as haskell } from 'shiki/langs/haskell.mjs'
export { default as ini } from 'shiki/langs/ini.mjs'
export { default as kotlin } from 'shiki/langs/kotlin.mjs'
// export { default as latex } from 'shiki/langs/latex.mjs'
// export { default as log } from 'shiki/langs/log.mjs'
export { default as lua } from 'shiki/langs/lua.mjs'
// export { default as make } from 'shiki/langs/make.mjs'
// export { default as matlab } from 'shiki/langs/matlab.mjs'
// export { default as mermaid } from 'shiki/langs/mermaid.mjs'
// export { default as nginx } from 'shiki/langs/nginx.mjs'
// export { default as objc } from 'shiki/langs/objective-c.mjs'
// export { default as objcpp } from 'shiki/langs/objective-cpp.mjs'
// export { default as pascal } from 'shiki/langs/pascal.mjs'
// export { default as perl } from 'shiki/langs/perl.mjs'
// export { default as powershell } from 'shiki/langs/powershell.mjs'
// export { default as prisma } from 'shiki/langs/prisma.mjs'
// export { default as proto } from 'shiki/langs/proto.mjs'
// export { default as ruby } from 'shiki/langs/ruby.mjs'
export { default as rust } from 'shiki/langs/rust.mjs'
// export { default as systemd } from 'shiki/langs/systemd.mjs'
// export { default as toml } from 'shiki/langs/toml.mjs'
// export { default as typespec } from 'shiki/langs/typespec.mjs'
// export { default as vb } from 'shiki/langs/vb.mjs'
// export { default as wenyan } from 'shiki/langs/wenyan.mjs'
// export { default as zig } from 'shiki/langs/zig.mjs'
